version: '3'

vars:
  PYTHON: poetry run python

tasks:
  # Default task - show help
  default:
    desc: Show available tasks (default)
    cmds:
      - task --list-all

  # ====================
  # Setup & Environment
  # ====================
  setup:install:
    desc: Install dependencies using Poetry
    cmds:
      - poetry install

  setup:update:
    desc: Update dependencies
    cmds:
      - poetry update

  setup:info:
    desc: Show environment info
    cmds:
      - poetry env info
      - poetry show --tree

  setup:shell:
    desc: Start Poetry shell
    cmds:
      - poetry shell

  # ====================
  # Processing Pipeline
  # ====================
  pipeline:process:
    desc: Process raw PDFs (identify and organize)
    cmds:
      - "{{.PYTHON}} script/run_pipeline.py --step process {{.CLI_ARGS}}"

  pipeline:extract:
    desc: Extract individual cards as images
    cmds:
      - "{{.PYTHON}} script/run_pipeline.py --step extract {{.CLI_ARGS}}"

  pipeline:backside:
    desc: Add default backsides to cards
    cmds:
      - "{{.PYTHON}} script/run_pipeline.py --step backsides {{.CLI_ARGS}}"

  pipeline:urls:
    desc: Generate URL CSV for TTS
    cmds:
      - "{{.PYTHON}} script/run_pipeline.py --step urls {{.CLI_ARGS}}"

  pipeline:all:
    desc: Run complete pipeline (process → extract → backside → urls)
    cmds:
      - "{{.PYTHON}} script/run_pipeline.py --step all {{.CLI_ARGS}}"
  
  pipeline:metadata:
    desc: Generate output metadata YAML
    cmds:
      - "{{.PYTHON}} script/generate_metadata.py {{.CLI_ARGS}}"

  # ====================
  # Development Tools
  # ====================
  dev:test:
    desc: Run tests
    cmds:
      - poetry run pytest tests/

  dev:lint:
    desc: Run linting
    cmds:
      - poetry run flake8 script/

  dev:format:
    desc: Format code with black
    cmds:
      - poetry run black script/

  dev:clean:
    desc: Clean generated files and cache
    cmds:
      - cmd: powershell -Command "Remove-Item -Recurse -Force **/__pycache__ -ErrorAction SilentlyContinue"
        platforms: [windows]
      - cmd: rm -rf **/__pycache__
        platforms: [linux, darwin]
