version: '3'

vars:
  PYTHON: poetry run python

tasks:
  # Default task - show help
  default:
    desc: Show available tasks (default)
    cmds:
      - task --list-all

  # ====================
  # Setup & Environment
  # ====================
  setup:install:
    desc: Install dependencies using Poetry
    cmds:
      - poetry install

  setup:update:
    desc: Update dependencies
    cmds:
      - poetry update

  setup:info:
    desc: Show environment info
    cmds:
      - poetry env info
      - poetry show --tree

  setup:shell:
    desc: Start Poetry shell
    cmds:
      - poetry shell

  # ====================
  # Processing Pipeline
  # ====================
  pipeline:process:
    desc: Process raw PDFs (identify and organize)
    cmds:
      - "{{.PYTHON}} script/process_raw_pdfs.py {{.CLI_ARGS}}"

  pipeline:extract:
    desc: Extract individual cards as images
    cmds:
      - "{{.PYTHON}} script/extract_pages.py {{.CLI_ARGS}}"

  pipeline:backside:
    desc: Add default backsides to cards
    cmds:
      - "{{.PYTHON}} script/add_default_backsides.py {{.CLI_ARGS}}"

  pipeline:urls:
    desc: Generate URL CSV for TTS
    cmds:
      - "{{.PYTHON}} script/generate_urls.py {{.CLI_ARGS}}"

  pipeline:all:
    desc: Run complete pipeline (process → extract → backside → urls)
    cmds:
      - task: pipeline:process
      - task: pipeline:extract
      - task: pipeline:backside
      - task: pipeline:urls

  # ====================
  # Development Tools
  # ====================
  dev:test:
    desc: Run tests
    cmds:
      - poetry run pytest tests/

  dev:lint:
    desc: Run linting
    cmds:
      - poetry run flake8 script/

  dev:format:
    desc: Format code with black
    cmds:
      - poetry run black script/

  dev:clean:
    desc: Clean generated files and cache
    cmds:
      - cmd: powershell -Command "Remove-Item -Recurse -Force **/__pycache__ -ErrorAction SilentlyContinue"
        platforms: [windows]
      - cmd: rm -rf **/__pycache__
        platforms: [linux, darwin]

  # ====================
  # Convenience Aliases (hidden from list, but work when typed)
  # ====================
  install:
    cmds:
      - task: setup:install

  process:
    cmds:
      - task: pipeline:process
        vars: {CLI_ARGS: "{{.CLI_ARGS}}"}

  extract:
    cmds:
      - task: pipeline:extract
        vars: {CLI_ARGS: "{{.CLI_ARGS}}"}

  all:
    cmds:
      - task: pipeline:all

  test:
    cmds:
      - task: dev:test
