"""Analyze card structure by extracting raw text from sample cards"""
import sys
from pathlib import Path
import logging
from PIL import Image
import pytesseract

# Add script directory to path
script_dir = Path(__file__).parent
sys.path.insert(0, str(script_dir / 'src'))


def extract_card_text(image_path: Path) -> str:
    """Extract all text from card image using OCR"""
    try:
        image = Image.open(image_path)
        
        # Try to use tesseract OCR
        text = pytesseract.image_to_string(image, config='--psm 6')
        
        if not text or len(text.strip()) < 10:
            return "ERROR: No text extracted or text too short"
        
        return text
    except pytesseract.TesseractNotFoundError:
        return "ERROR: Tesseract not installed. Please install tesseract-ocr from https://github.com/UB-Mannheim/tesseract/wiki"
    except Exception as e:
        return f"ERROR: {e}"


def analyze_card_type(output_dir: Path, card_type: str, teams: list, max_samples: int = 2):
    """Analyze multiple cards of a specific type across teams"""
    print(f"\n{'='*80}")
    print(f"CARD TYPE: {card_type}")
    print(f"{'='*80}\n")
    
    sample_count = 0
    
    for team in teams:
        team_path = output_dir / team / card_type
        if not team_path.exists():
            continue
        
        # Get front images
        front_images = sorted(team_path.glob('*_front.jpg'))
        
        for img_path in front_images[:max_samples]:
            sample_count += 1
            print(f"\n{'-'*80}")
            print(f"SAMPLE {sample_count}: {team}/{card_type}/{img_path.name}")
            print(f"{'-'*80}\n")
            
            text = extract_card_text(img_path)
            print(text)
            print(f"\n[END OF SAMPLE {sample_count}]")
            
        if sample_count >= max_samples * len(teams):
            break


def main():
    """Main entry point"""
    # Setup logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    project_root = Path(__file__).parent.parent
    output_dir = project_root / 'output'
    docs_dir = project_root / 'docs' / 'card-structure'
    docs_dir.mkdir(parents=True, exist_ok=True)
    
    # Sample teams to analyze
    teams = ['kasrkin', 'deathwatch', 'battleclade', 'blooded', 'wrecka-krew']
    
    # Card types to analyze
    card_types = [
        'datacards',
        'equipment',
        'faction-rules',
        'strategy-ploys',
        'firefight-ploys',
        'operatives'
    ]
    
    # Analyze each card type
    for card_type in card_types:
        output_file = docs_dir / f"{card_type}.md"
        
        print(f"\nAnalyzing {card_type}...")
        
        # Redirect stdout to file
        original_stdout = sys.stdout
        with open(output_file, 'w', encoding='utf-8') as f:
            sys.stdout = f
            
            print(f"# Card Structure Analysis: {card_type.upper()}")
            print(f"\nGenerated by analyzing sample cards from multiple teams.")
            print(f"This helps understand text layout for OCR extraction.\n")
            
            analyze_card_type(output_dir, card_type, teams, max_samples=2)
        
        sys.stdout = original_stdout
        print(f"Created {output_file}")


if __name__ == '__main__':
    main()
