"""Build a dev loader card that STAMPS the composed model script (from
dev/ktui-model-composed.lua) onto a model -- like the physical extender does,
but it's OUR composed script (patched real extender + our extension).

It mirrors the extender's stamp sequence: setLuaScript -> reload -> addTag
KTUIMini -> setOwningPlayer(clicking player's steam_id). That last call is the
card-side owner assignment the real pipeline will also do.

TEST FLOW in TTS:
  1. Put a KTUI mini down and run our normal "Load stats" (populates state).
  2. Put it on this pad -> right-click -> "Load KTUI composed to model".
  3. Verify: dynamic colour health bar, order token, table Save/Load + Ready
     Operatives work WITHOUT the physical extender, and a "KT: extension OK"
     context item appears (proves our appended code runs alongside the extender).

Re-run after rebuilding the composed script:
    python dev/build_ktui_composed_loader.py
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
COMPOSED = HERE / "ktui-model-composed.lua"
OUT = HERE / "ktui-composed-loader-card.lua"
OUT_JSON = HERE / "ktui-composed-loader-card.json"
LOADER_GUID = "5b7a50"


def pick_bracket_level(code: str) -> int:
    level = 1
    while ("]" + "=" * level + "]") in code:
        level += 1
    return level


def build_loader(composed: str) -> str:
    level = pick_bracket_level(composed)
    eq = "=" * level
    embedded = f"[{eq}[\n{composed}\n]{eq}]"
    return f"""-- kt-datacards: KTUI Composed Loader (POC)  [GENERATED by dev/build_ktui_composed_loader.py]
-- Stamps our composed model script onto a model (mirrors the physical extender:
-- setLuaScript -> reload -> addTag KTUIMini -> setOwningPlayer). Load stats on the
-- model FIRST so its KTUI state exists before stamping.

local KTUI_COMPOSED = {embedded}

function broadcastToColor(msg, pc, col)
    if pc and Player[pc] then Player[pc].broadcast(msg, col or {{1, 1, 1}}) end
end

function findModelOnCard()
    local pos = self.getPosition()
    local hits = Physics.cast({{
        origin = Vector(pos.x, pos.y + 1.5, pos.z), direction = {{0, -1, 0}},
        type = 2, size = {{2, 2, 2}}, max_distance = 3,
    }})
    for _, hit in ipairs(hits) do
        local obj = hit.hit_object
        if obj and obj ~= self and (obj.type == "Custom_Model" or obj.type == "Figurine") then
            return obj
        end
    end
    return nil
end

function loadComposedToModel(playerColor)
    local model = findModelOnCard()
    if not model then
        broadcastToColor("Place a model on this pad first.", playerColor, {{1, 0.6, 0}})
        return
    end
    model.setLuaScript(KTUI_COMPOSED)
    local steamId = Player[playerColor] and Player[playerColor].steam_id or nil
    Wait.frames(function()
        if not model then return end
        model.reload()
        if not model.hasTag("KTUIMini") then model.addTag("KTUIMini") end
        if steamId then
            Wait.frames(function()
                if model then model.call("setOwningPlayer", steamId) end
            end, 30)
        end
    end, 5)
    broadcastToColor("Stamped composed KTUI script + set owner. Right-click the model to test.",
        playerColor, {{0.2, 0.85, 0.3}})
end

function onLoad()
    self.addContextMenuItem("Load KTUI composed to model", loadComposedToModel)
end
"""


def main() -> None:
    if not COMPOSED.exists():
        raise SystemExit(f"missing {COMPOSED.relative_to(ROOT)} -- run build_ktui_model_script.py first")
    composed = COMPOSED.read_text(encoding="utf-8").rstrip("\n")
    loader = build_loader(composed)
    OUT.write_text(loader, encoding="utf-8")
    pad = {
        "Name": "BlockSquare",
        "Transform": {"posX": 0.0, "posY": 1.0, "posZ": 0.0, "rotX": 0.0, "rotY": 0.0,
                      "rotZ": 0.0, "scaleX": 4.0, "scaleY": 0.3, "scaleZ": 4.0},
        "Nickname": "KTUI Composed Loader",
        "Description": "Load stats on a KTUI mini first, then put it here and "
                       "right-click -> 'Load KTUI composed to model'.",
        "ColorDiffuse": {"r": 0.35, "g": 0.2, "b": 0.5}, "Locked": True, "Grid": True,
        "Snap": True, "Autoraise": True, "Tooltip": True,
        "LuaScript": loader, "LuaScriptState": "", "XmlUI": "", "GUID": LOADER_GUID,
    }
    save = {
        "SaveName": "KTUI Composed Loader", "Date": "", "VersionNumber": "", "GameMode": "",
        "GameType": "", "GameComplexity": "", "Tags": [], "Gravity": 0.5, "PlayArea": 0.5,
        "Table": "", "Sky": "", "Note": "", "TabStates": {}, "LuaScript": "", "LuaScriptState": "",
        "XmlUI": "", "ObjectStates": [pad],
    }
    with OUT_JSON.open("w", encoding="utf-8", newline="\n") as f:
        json.dump(save, f, indent=2, ensure_ascii=False)
    print("wrote", OUT.name, "and", OUT_JSON.name)


if __name__ == "__main__":
    main()
