-- kt-datacards: Attack Callout Loader (POC)  [GENERATED by dev/build_callout_loader.py]
-- Put a KTUI mini (stats already loaded) on this pad, then right-click ->
-- "Load attack callout to model". Injects the callout block (START/END markers);
-- loading again UPDATES it in place. Adds context items "Ranged attacks" /
-- "Close combat attacks" and two rebindable Game Keys.

local AC_START = "-- START KT_ATTACK_CALLOUT_V1"
local AC_END   = "-- END KT_ATTACK_CALLOUT_V1"

local AC_CODE = [=[
-- START KT_ATTACK_CALLOUT_V1
--[[ Weapon Attack Callout (POC): two grouped chat call-outs + two hotkeys.
Reads state.info.weapons (name/plain_name/stats.ATK/HIT/DMG/WR). Chat-only.
Injured shows the +1 hit in red with a medical cross. Chains onLoad. ]]
do
  local COL_R = "1E87FF"   -- our [R] ranged tag colour
  local COL_M = "F4641D"   -- our [M] melee tag colour

  local function acRanged(w)
    local n = (w and w.name) or ""
    if n:find(COL_R, 1, true) then return true end
    if n:find(COL_M, 1, true) then return false end
    local wr = (w and w.stats and w.stats.WR) or ""
    return wr:find("Range", 1, true) ~= nil
  end

  -- Match the KTUI wound-bar injured state (state.wounds < max/2).
  local function acInjured()
    if not state then return false end
    local cur  = tonumber(state.wounds)
    local maxw = tonumber(state.stats and state.stats.Wounds)
    if not cur or not maxw or maxw <= 0 then return false end
    return cur < maxw / 2
  end

  -- Non-injured -> "3+"; injured -> red "4+ ✚" (medical cross = penalty applied).
  local function acHit(hit, injured)
    hit = tostring(hit or "?")
    if not injured then return hit end
    local base = tonumber(hit:match("%d+"))
    local val  = base and ((base + 1) .. "+") or hit
    return "[FF0000]" .. val .. " ✚[-]"
  end

  local function acLine(w, injured)
    local tag  = acRanged(w) and ("[" .. COL_R .. "]R[-]") or ("[" .. COL_M .. "]M[-]")
    local name = (w and (w.plain_name or w.name)) or "?"
    local s    = (w and w.stats) or {}
    local line = string.format("%s %s   ATK: %s @ %s   DMG: %s",
      tag, name, tostring(s.ATK or "?"), acHit(s.HIT, injured), tostring(s.DMG or "?"))
    local wr = tostring(s.WR or "")
    if wr ~= "" and wr ~= "-" then line = line .. "   WR: " .. wr end
    return line
  end

  function acCallout(ranged)
    local weapons = (state and state.info and state.info.weapons) or {}
    local injured = acInjured()
    local nm = self.getName()
    local opName = (nm ~= nil and nm ~= "" and nm)
      or (state and state.info and state.info.name) or "Operative"
    local title = ranged and "[1E87FF]RANGED[-]" or "[F4641D]MELEE[-]"
    local lines = { title .. " -- " .. opName }
    for _, w in ipairs(weapons) do
      if acRanged(w) == ranged then lines[#lines + 1] = acLine(w, injured) end
    end
    if #lines == 1 then
      lines[#lines + 1] = ranged and "No ranged attacks." or "No melee attacks."
    end
    printToAll(table.concat(lines, "\n"), { 1, 1, 1 })
  end

  function acCalloutRanged(_) acCallout(true) end
  function acCalloutMelee(_)  acCallout(false) end

  local _ac_prev_onLoad = onLoad
  function onLoad(...)
    if _ac_prev_onLoad then pcall(_ac_prev_onLoad, ...) end
    self.addContextMenuItem("Ranged attacks", function(pc) acCallout(true) end)
    self.addContextMenuItem("Close combat attacks", function(pc) acCallout(false) end)
    if Global.getVar("KT_CALLOUT_R_HOTKEY") ~= true then
      Global.setVar("KT_CALLOUT_R_HOTKEY", true)
      addHotkey("KT: Call out ranged attacks", function(color, hovered)
        if hovered ~= nil and hovered.call ~= nil then hovered.call("acCalloutRanged", {}) end
      end, false)
    end
    if Global.getVar("KT_CALLOUT_M_HOTKEY") ~= true then
      Global.setVar("KT_CALLOUT_M_HOTKEY", true)
      addHotkey("KT: Call out melee attacks", function(color, hovered)
        if hovered ~= nil and hovered.call ~= nil then hovered.call("acCalloutMelee", {}) end
      end, false)
    end
  end
end
-- END KT_ATTACK_CALLOUT_V1
]=]

function broadcastToColor(msg, pc, col)
    if pc and Player[pc] then Player[pc].broadcast(msg, col or {1, 1, 1}) end
end

function findModelOnCard()
    local pos = self.getPosition()
    local hits = Physics.cast({
        origin = Vector(pos.x, pos.y + 1.5, pos.z), direction = {0, -1, 0},
        type = 2, size = {2, 2, 2}, max_distance = 3,
    })
    for _, hit in ipairs(hits) do
        local obj = hit.hit_object
        if obj and obj ~= self and obj.hasTag("KTUIMini") then return obj end
    end
    for _, hit in ipairs(hits) do
        local obj = hit.hit_object
        if obj and obj ~= self and obj.type == "Custom_Model" then return obj end
    end
    for _, hit in ipairs(hits) do
        local obj = hit.hit_object
        if obj and obj ~= self and obj.type == "Figurine" then return obj end
    end
    return nil
end

function addCalloutToModel(playerColor)
    local model = findModelOnCard()
    if not model then
        broadcastToColor("Place a model on this pad first.", playerColor, {1, 0.6, 0})
        return
    end
    local lua = model.getLuaScript() or ""
    local sStart = lua:find(AC_START, 1, true)
    if sStart then
        local _, eEnd = lua:find(AC_END, sStart, true)
        if not eEnd then
            broadcastToColor("Callout block corrupt (no END); left as-is.", playerColor, {1, 0.6, 0})
            return
        end
        local before = (lua:sub(1, sStart - 1)):gsub("%s+$", "")
        local after  = lua:sub(eEnd + 1)
        model.setLuaScript(before .. "\n\n" .. AC_CODE .. after)
        Wait.frames(function() if model ~= nil then model.reload() end end, 10)
        broadcastToColor("Attack callout updated.", playerColor, {0.2, 0.85, 0.3})
        return
    end
    model.setLuaScript(lua .. "\n\n" .. AC_CODE)
    Wait.frames(function() if model ~= nil then model.reload() end end, 10)
    broadcastToColor("Attack callout added. Right-click -> Ranged/Close combat attacks.", playerColor, {0.2, 0.85, 0.3})
end

function onLoad()
    self.addContextMenuItem("Load attack callout to model", addCalloutToModel)
end
